### ISSUE TITLE
Configurable priority

### ISSUE THREAD

**Issue by cdfa** [Nefelim4ag/systemd-swap#110]
Hi, I would like to run this in conjunction with a swap partition on my HDD. However, the swapfiles that are created on my SSD have a negative priority, so they won't be used first.
The partition on my HDD is mainly to prevent system freezes when no more swap files can be created because my SSD is full, so I want it to have a lower priority.

Could you make the priority of swap files configurable?

**Comment by Jarel1337** [comment]
The easiest way to fix this would be to set your HDDs swap priority to a low value. Configurating the swapfiles created by systemd-swap is doable but I think it'll just confuse people and/or lead to missconfigurations.
If someone is able to provide a valid usecase I can of course implement it

**Comment by cdfa** [comment]
With `swapon`, you can only give priorities between -1 and some high number, but the swap file priority is -3, so it seems I can't set my HDD's priority lower than that. :(

**Comment by Jarel1337** [comment]
This is interesting, I'll need to do some research as to how we can get such negative priorities but you can't. If this is as you say (and some searching around says that it is) I'll add an option to resolve this 👍.

**Comment by cdfa** [comment]
I think the system just gives negative priorities when no priority is specified when creating the swap space.
