### ISSUE TITLE
swapFC on f2fs

### ISSUE THREAD

**Issue by zenofile** [Nefelim4ag/systemd-swap#114]
I was evaluating the use of zswap backed by a swap file on top of f2fs and saw the discussions about swap file holes earlier so I decided to do some testing:

```console
$ findmnt /
TARGET SOURCE    FSTYPE OPTIONS
/      /dev/sda1 f2fs   rw,noatime,lazytime,background_gc=on,nodiscard,no_heap,user_xattr,inline_xattr,acl,inline_data,inline_dentry,flush_merge,extent_cache,mode=adaptive,active_logs=6,alloc_mode=default,fsync_mode=posix
$ fallocate -l $((1024*1024*128)) swap
$ stat swap
  File: swap
  Size: 134217728       Blocks: 262408     IO Block: 4096   regular file
Device: 801h/2049d      Inode: 135800      Links: 1
Access: (0600/-rw-------)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2020-06-06 20:51:16.329395705 +0200
Modify: 2020-06-06 20:51:16.333395649 +0200
Change: 2020-06-06 20:51:16.333395649 +0200
 Birth: -
$ mkswap swap 
Setting up swapspace version 1, size = 128 MiB (134213632 bytes)
no label, UUID=89fcb86a-cfa1-4783-bbaf-5360813c4576
$ swapon swap
swapon: /root/swap: swapon failed: Invalid argument
$ dmesg | tail -n1
[ 4007.446138] swapon: swapfile has holes
```

When using `truncate`, `swapon` actually complains about holes - using `dd`, everything seems to work as expected.

This was done on `5.4.0-1011-raspi` (Ubuntu) and `5.6.16-300.fc32.x86_64` (Fedora).

After skimming the code I presume systemd-swap would try to use fallocate for allocating on f2fs, which in return would render swapFC not working on top of it if that assumption is correct.

Should there be an exception for f2fs as well?

**Comment by Jarel1337** [comment]
You can create a pull request if you want or I could add it myself. Thank you for testing 👍
