### ISSUE TITLE
systemd service does not start on Ubuntu 18.04

### ISSUE THREAD

**Issue by Derppening** [Nefelim4ag/systemd-swap#118]
When trying to start the service via `systemd` on Ubuntu 18.04, the service will fail to start with the following output:

```
Jun 08 12:21:29 david-server systemd[1]: Started Manage swap spaces on zram, files and partitions..
Jun 08 12:21:29 david-server systemd[1]: systemd-swap.service: Main process exited, code=killed, status=31/SYS
Jun 08 12:21:29 david-server systemd[1]: systemd-swap.service: Failed with result 'signal'.
Jun 08 12:21:29 david-server systemd[1]: systemd-swap.service: Consumed 19ms CPU time
```

Running the script in a standalone fashion (via `/usr/bin/systemd-swap start`) works.

In addition, when executing `systemctl daemon-reload`, the following message appears:

```
Jun 08 12:22:40 david-server systemd[1]: /lib/systemd/system/systemd-swap.service:25: Unknown system call group, ignoring: @system-service
```

Commenting out the offending line (`systemd-swap.service:25`) will allow the service to start properly.

**Comment by Jarel1337** [comment]
Yes, it seems that the `@system-service` filter isn't available on Ubuntu 18.04 nor Centos7.

**Comment by Jarel1337** [comment]
I updated the release notes to mention this regression, but I won't fix it since these older versions are on their way out (and can easily be fixed as previously noted).

**Comment by Derppening** [comment]
No problem, thanks for the quick update!
