### ISSUE TITLE
Update swap.conf and create a manpage

### ISSUE THREAD

**Issue by Jarel1337** [Nefelim4ag/systemd-swap#123]
Since we have the systemd name we should try to live up to it. For that we should try to mimic (for example) `resolved.conf` `journald.conf` and `networkd.conf`. Since we'll be removing the comments from `swap.conf` we will need a `man 5 swap.conf` and we should also have `man 8 systemd-swap`.
In the transition period we should also fill out our `readme.md` with configuration options since the manpages will likely not be available online for some time.

We could also create a `swapctl` (with accompanying man page), but that is an if and probably for a later date.

**Comment by Jarel1337** [comment]
We'll scrap that part about adding things to the readme since `swap-default.conf` has enough information.

**Comment by Jarel1337** [comment]
I'll release a new version very soon @zenofile anything you want to implement before?

**Comment by zenofile** [comment]
Not particularly, no. Go ahead.

Vilgot Fredenberg <notifications@github.com> schrieb am Sa., 13. Juni 2020,
15:59:
