### ISSUE TITLE
Questions about what is considered "free" memory

### ISSUE THREAD

**Issue by terencode** [Nefelim4ag/systemd-swap#127]
Here are my current stats:
```
              total        used        free      shared  buff/cache   available
Mem:           15Gi       7,3Gi       576Mi       727Mi       7,7Gi       6,1Gi
```

When I started systemd-swap, here is what it did:
```
juin 12 00:33:18 terence-desktop systemd-swap[668294]: INFO: swapFC: on-demand swap activation at >12001 MiB memory usage
juin 12 00:33:19 terence-desktop systemd-swap[668294]: INFO: swapFC: free ram: 4 < 25 - allocate chunk: 1
```
First question: I only see one chunk allocated in the log (configured to be 1GB):
```
juin 12 00:33:21 terence-desktop systemd-swap[668711]: Configure l'espace d'échange (swap) en version 1, taille = 1024 MiB (1073737728 octet>
```

So why does my swap is 4.6GB ? Is it somehow due to zram being enabled?
Prior to enabling systemd-swap, there was no swap.
```
Swap:         4,6Gi       6,0Mi       4,6Gi
```

Second question: what is "free" ram here? It looks like it's using the "free" stat which is `576Mi` but shouldn't it use "available" instead? 
If I understand correctly, when "free" is low, it will just use the memory allocated for "buff/cache" so until all of it is used there is no need to activate swap yet.

**Comment by Jarel1337** [comment]
Yes, you should never combine zram with zswap or with swapfc and zram is what is causing your swap usage yo seem so high.

We track ram usage based on free since we potentially want to swap out disk cache or swap out something else and keep the disk cache in memory. Disk cache is really important for performance.

**Comment by terencode** [comment]
Ok, thanks for your answers.
So the only thing you are ok to combine is  zswap + swapfc ? 

I see you recently introduced a warning message when mixing zswap with zram (071930c5c7a7492424c157134bac2e6f0ccd9c88). Maybe you should also add one with zram + zswapfc ?

**Comment by terencode** [comment]
Closing since all questions were answered and #127 happened, thanks!
