### ISSUE TITLE
4.2.0 regression: multiple zram devices all get zram_size capacity

### ISSUE THREAD

**Issue by chungy** [Nefelim4ag/systemd-swap#134]
In 4.1.0 and older, the zram_size property got divided into smaller zram devices. The default of `$((RAM_SIZE / 4))` resulted in me only having 8GB of swap (32GB of real RAM). Now on 4.2.0, I get 94GB of swap (still 32GB of real RAM, 12 CPU threads).

**Comment by zenofile** [comment]
I think this was introduced with 762dac334b295ddc633c213d8e93b031854ca84e where `zram_size=$(( zram_size / zram_count ))` was mistakenly removed.

**Comment by chungy** [comment]
Thanks, works :)
