### ISSUE TITLE
systemd-swap doesn't see swap partitions due to systemd service restrictions

### ISSUE THREAD

**Issue by tycho** [Nefelim4ag/systemd-swap#137]
I have a system with a swap partition on a SATA block device. Due to the way `systemd-swap.service` is specified, the `swapd_auto_swapon` feature isn't able to discover it via `blkid -t TYPE=swap` (the attempt by `blkid` to access `/dev/sd*` for all the devices fails with `EACCES`).

To fix this on my local system I've had to do this:
```
# cat /etc/systemd/system/systemd-swap.service.d/devices.conf
[Service]
DeviceAllow=block-sd r
```
I don't see anything in the documentation mentioning this, so either there's a bug in the service definition or a documentation gap.

Also, if it was on an NVMe partition, it looks like I would need to have an additional line:
```
DeviceAllow=block-blkext r
```

**Comment by Jarel1337** [comment]
Aa, good catch. Yes this is an oversight.
