### ISSUE TITLE
mkswap /dev/zram0 fail

### ISSUE THREAD

**Issue by joseafga** [Nefelim4ag/systemd-swap#138]
After update from **4.1.0** to  **4.2.1** /dev/zram0 is no longer mounted as swap.

```
$ lsblk
NAME     MAJ:MIN RM   SIZE RO TYPE  MOUNTPOINT
sda        8:0    0 223,6G  0 disk  
...
zram0    253:0    0   1,9G  0 disk  
zram1    253:1    0   1,9G  0 disk  [SWAP]
```
I use bash command trace to try found something and see `gen_swap_unit` function is no executed, so I removed redirection of mkswap to see the error.  
[systemd-swap.log](https://github.com/Nefelim4ag/systemd-swap/files/4783249/systemd-swap.log)

Here is when errors occurs:
```
+ mkswap /dev/zram0
mkswap: cannot open /dev/zram0: Operation not permitted
+ systemctl daemon-reload
+ systemctl start ''
Failed to mangle name: Invalid argument
Failed to expand names: Invalid argument
```

I tried to return some changes that occurred between the versions as the target unit of systemd but unsuccessfully.

**Comment by Jarel1337** [comment]
I'm assuming that zram is only created by systemd-swap?
Does removing the line containing "`DeviceAllow`" in `systemd-swap.service` fix this issue?

**Comment by joseafga** [comment]
> I'm assuming that zram is only created by systemd-swap?
> Does removing the line containing "`DeviceAllow`" in `systemd-swap.service` fix this issue?

Right.
If I remove only `DeviceAllow` both zram fail but if I change all the `systemd-swap.service` for the version 4.1.0 it works.

**Comment by joseafga** [comment]
After some trial and error I removed `DeviceAllow` and `ProtectClock` lines. Now works fine again.
but is a bit stranger ... and another thing I notice is if i run `systemctl daemon-reload` before mkswap in script, all work fine too.
