### ISSUE TITLE
Unstable zram enabling

### ISSUE THREAD

**Issue by felixonmars** [Nefelim4ag/systemd-swap#14]
I've noticed that ~30% of the time, zram didn't get enabled, and the log:

```
Jul 07 23:05:17 flygon.felixc.at systemd-swap.sh[335]: [lzo] lz4
Jul 07 23:05:17 flygon.felixc.at systemd-swap.sh[335]: /dev/sda2 >> /run/lock/systemd-swap.dev
Jul 07 23:05:17 flygon.felixc.at systemd-swap.sh[335]: 1 >> /sys/block/zram0/reset
Jul 07 23:05:17 flygon.felixc.at systemd-swap.sh[335]: lz4 >> /sys/block/zram0/comp_algorithm
Jul 07 23:05:17 flygon.felixc.at systemd-swap.sh[335]: 13618343K >> /sys/block/zram0/disksize
Jul 07 23:05:17 flygon.felixc.at systemd-swap.sh[335]: mkswap: error: swap area needs to be at least 40 KiB
Jul 07 23:05:17 flygon.felixc.at systemd-swap.sh[335]: Usage:
Jul 07 23:05:17 flygon.felixc.at systemd-swap.sh[335]: mkswap [options] device [size]
Jul 07 23:05:17 flygon.felixc.at systemd-swap.sh[335]: Options:
Jul 07 23:05:17 flygon.felixc.at systemd-swap.sh[335]: -c, --check               check bad blocks before creating the swap area
Jul 07 23:05:17 flygon.felixc.at systemd-swap.sh[335]: -f, --force               allow swap size area be larger than device
Jul 07 23:05:17 flygon.felixc.at systemd-swap.sh[335]: -p, --pagesize SIZE       specify page size in bytes
Jul 07 23:05:17 flygon.felixc.at systemd-swap.sh[335]: -L, --label LABEL         specify label
Jul 07 23:05:17 flygon.felixc.at systemd-swap.sh[335]: -v, --swapversion NUM     specify swap-space version number
Jul 07 23:05:17 flygon.felixc.at systemd-swap.sh[335]: -U, --uuid UUID           specify the uuid to use
Jul 07 23:05:17 flygon.felixc.at systemd-swap.sh[335]: -V, --version             output version information and exit
Jul 07 23:05:17 flygon.felixc.at systemd-swap.sh[335]: -h, --help                display this help and exit
```

My wild guess would be that mkswap was called too early (before the disksize actually took effect). I'll add some workaround and see if that works.

**Comment by felixonmars** [comment]
Looks like there are still some cases that it failed to enable zram:
```
May 12 09:53:53 flygon.felixc.at systemd-swap.sh[475]: zramctl: /dev/zram0: failed to reset: Device or resource busy
```

This happens ~ 10% of total reboots recently, so I have to reopen the issue :(

**Comment by Nefelim4ag** [comment]
Hi, felix, For a long time I did not hear you =)
It happens with new zramctl from util-linux package?

**Comment by felixonmars** [comment]
Hi, long time no see :D
Yes, it's from util-linux 2.26.2.

**Comment by Nefelim4ag** [comment]
@felixonmars,
Try it
https://github.com/Nefelim4ag/systemd-swap/commit/e4127299abb200804359a12e8eac5b10770949d5

**Comment by felixonmars** [comment]
Thanks, I'll get back to you some days later to test :)

**Comment by felixonmars** [comment]
Today I got an infinite loop of the following error in journal:

```
Jun 03 00:25:48 flygon.felixc.at systemd-swap.sh[375]: zramctl: /dev/zram0: failed to set number of streams: No such file or directory
Jun 03 00:25:49 flygon.felixc.at systemd-swap.sh[375]: zramctl: /dev/zram0: failed to set number of streams: No such file or directory
Jun 03 00:25:50 flygon.felixc.at systemd-swap.sh[375]: zramctl: /dev/zram0: failed to set number of streams: No such file or directory
...
```

Any hints?

**Comment by Nefelim4ag** [comment]
O_o, i can't imagine whats happen, it a problem with zramctl or with kernel module.
Because i've just try infinite resetup zram device until succesful -.- through zramctl, and as i remember "/etc/modprobe.d/90-systemd-swap.conf" must auto insert module to the kernel.

May be you have a problem with systemd-modules-load.service ? and zram module not automatical loaded while system bootup?

**Comment by felixonmars** [comment]
I tried to unload and load the module manually, and restarting systemd-swap, etc, but still getting the infinite loop. Not sure what is wrong, though :(

**Comment by Nefelim4ag** [comment]
@felixonmars, -.- sorry, but i really don't know what can happen in your system -.-

**Comment by felixonmars** [comment]
After a month and so I would like to say it's stable now. Would you mind tag a new minor release for it?

Thanks :)

**Comment by Nefelim4ag** [comment]
Awesome =)
Done 2.25.2
