### ISSUE TITLE
failed to load after update Arch Linux

### ISSUE THREAD

**Issue by JesterMEV** [Nefelim4ag/systemd-swap#150]
![изображение](https://user-images.githubusercontent.com/32267296/85857885-1b77b080-b7d4-11ea-915a-957754e8850d.png)
zram doesn't start after the last update
![изображение](https://user-images.githubusercontent.com/32267296/85858135-8de89080-b7d4-11ea-8634-83da3f127a23.png)

**Comment by zenofile** [comment]
The official Arch Linux PKGBUILD seems to be still using `PREFIX` for setting a buildroot.

https://github.com/Nefelim4ag/systemd-swap/pull/145 introduced a change in handling hard coded paths. This can be fixed by using `DESTDIR` instead of `PREFIX` when building the package.

**Comment by pheiduck** [comment]
Have the same: [is not related to systemd](https://github.com/systemd/systemd/issues/16289)

**Comment by Brottweiler** [comment]
Reported here https://bugs.archlinux.org/task/67120?project=5&string=systemd-swap

**Comment by Jarel1337** [comment]
Fixed in 4.2.3-2

**Comment by pheiduck** [comment]
Still broken on Manjaro testing (updated today)

**Comment by Brottweiler** [comment]
@pheiduck Complain to Manjaro.

**Comment by JesterMEV** [comment]
@pheiduck arch linux fine

**Comment by pheiduck** [comment]
Only version `4.0.1-2` works which is in **stable** 
otherwise `zswap` or `swapfc` doesn’t work for my only `zram`
