### ISSUE TITLE
Add possibility to set path of swapfc_path in a home dir path

### ISSUE THREAD

**Issue by tyjak** [Nefelim4ag/systemd-swap#152]
I needed to set `swapfc_path` to a path in my home dir since my home dir is a disk partition with much more disk space, but the protection (`ProtectHome=read-only`) in `systemd-swap.service` file doesn't allow to do it...
Is it possible to remove this protection ? Are can you explain why is it necessary to protect Home dir for this service ?

Thank you in advance

**Comment by zenofile** [comment]
> Is it possible to remove this protection ? Are can you explain why is it necessary to protect Home dir for this service ?

Create a configuration fragment and override the setting:

`sudo systemctl edit systemd-swap.service`
```ini
[Service]
ProtectHome=no
```

**Comment by Jarel1337** [comment]
> I needed to set `swapfc_path` to a path in my home dir since my home dir is a disk partition with much more disk space, but the protection (`ProtectHome=read-only`) in `systemd-swap.service` file doesn't allow to do it...
> Is it possible to remove this protection ? Are can you explain why is it necessary to protect Home dir for this service ?
> 
> Thank you in advance
> 
> 

The reason is that unless "weird" configurations are wanted (such as in your case) there is zero **zero** reason to give the service uneeded access. One could even argue that read-only is too much. But as @zenofile points out this is really easy to configure yourself

**Comment by tyjak** [comment]
I understand. I'll use @zenofile solution.
Thank you both of you :)
