### ISSUE TITLE
swapon errors "swap file has holes"

### ISSUE THREAD

**Issue by pheiduck** [Nefelim4ag/systemd-swap#155]
On the latest version of systemd-swap on (manjaro testing) I'm only able to get `zram` to work, the other `swapfc` `zswap` doesn't work. On the version 4.0.1-2 all works fine. (I don't have tested other previous versions)

**Comment by pheiduck** [comment]
I can later post my Hardware Configuration. I use **btrfs** if this can help, to troubleshoot

**Comment by pheiduck** [comment]
[discussed on the manjaro forum](https://forum.manjaro.org/t/systemd-swap-failed-to-activate/151296/11)

**Comment by zenofile** [comment]
There was a botched PR (https://github.com/Nefelim4ag/systemd-swap/pull/140) modifying the btrfs code path, with the possible fix still being worked on (https://github.com/Nefelim4ag/systemd-swap/pull/144) as it seems.

**Comment by Jarel1337** [comment]
Since #144 hasn't seen an update in a while by the submitter could I fix it up and merge it.

**Comment by Jarel1337** [comment]
Whops, didn't mean to close this just yet.
Did c8431ddbd728e7da14eaa69362a2ef0becf6074d fix it for you?

**Comment by pheiduck** [comment]
@Jarel1337 I will give you Feedback when I‘m back at home. Should I use the version in the arch repo or git clone here?

**Comment by Jarel1337** [comment]
> @Jarel1337 I will give you Feedback when I‘m back at home. Should I use the version in the arch repo or git clone here?

Please use master ([aur package here](https://aur.archlinux.org/packages/systemd-swap-git/) or just make install)

**Comment by nathanielcwm** [comment]
Doesn't seem to be working for me I've tried deleting the old systemd-swap folder and rebooting the system and it keeps on errorring out for me.

**Comment by pheiduck** [comment]
@Jarel1337 same to me (like @nathanielcwm) installed via `make install`

**Comment by pheiduck** [comment]
newest version >` journalctl -p err -b swap File failed to activate`

**Comment by Jarel1337** [comment]
@nathanielcwm Are you also using btrfs?

**Comment by Jarel1337** [comment]
To temporary fix this you can set `swapfc_force_use_loop=true`

**Comment by Jarel1337** [comment]
Should be fixed by using dd instead of fallocate (I even forgot dd wasn't used for some filesystems, this should've happened long ago)

**Comment by pheiduck** [comment]
I hope it will fix it, the workaround: `swapfc_force_use_loop=true` show me invalide argument in `systemctl status systemd-swap.service`

Can also be Hardware related?

**Comment by Jarel1337** [comment]
> I hope it will fix it, the workaround: `swapfc_force_use_loop=true` show me invalide argument in `systemctl status systemd-swap.service`
> 
> Can also be Hardware related?

You will need to manually backport both commits for it to work, I would recommend just using master for now

**Comment by pheiduck** [comment]
Finally make install from master and the issue is gone. Thanks you so much @Jarel1337 !
I will wait until this is in arch Linux upstream repos.
