### ISSUE TITLE
systemd service: Operation not permitted

### ISSUE THREAD

**Issue by wallace11** [Nefelim4ag/systemd-swap#160]
Running with the provided (hardened) systemd service, I get the following error:

```
systemd-swap.service: Failed to set up CPU scheduling: Operation not permitted
systemd-swap.service: Failed at step SETSCHEDULER spawning /usr/bin/systemd-swap: Operation not permitted
systemd-swap.service: Main process exited, code=exited, status=214/SETSCHEDULER
systemd-swap.service: Failed with result 'exit-code'.
Failed to start Manage swap spaces on zram, files and partitions..
```

Tried to:

1. Recreate service: `systemctl disable systemd-swap && systemctl enable --now systemd-swap` - FAIL
2. Run manually: `sudo systemd-swap start` SUCCESS 

OS: Archlinuxarm
Package version: [4.2.3-2](https://archlinuxarm.org/packages/any/systemd-swap)
systemd version: [245.6-8](https://archlinuxarm.org/packages/armv7h/systemd)

**Comment by Jarel1337** [comment]
This is not our bug, but removing:
```
CPUSchedulingPolicy=fifo
CPUSchedulingPriority=20
```
from systemd-swap.service will resolve this.

**Comment by wallace11** [comment]
Thanks for the hint.
This is quite a strange behavior, so I'll try to elaborate as much as possible regarding how to fix it for future reference.

OS: Archlinuxarm
HW: Odroid XU4
Kernel: 4.14.180-1-ARCH

There are essentially two problems to solve, one with the scheduler not being set (discussed above) and one is related to #154. 
In order to solve it, we need to add a drop-in override by executing: `systemctl edit systemd-swap` which will effectively create `/etc/systemd/system/systemd-swap.service.d/override.conf` and let us edit it:

```
[Service]
CPUSchedulingPolicy=other
SystemCallErrorNumber=EPERM
```
**Note:** Changing `CPUSchedulingPriority` is unnecessary.

Then run `systemctl daemon-reload && systemctl restart systemd-swap` and it should work.

On a side note, I tried to investigate how to catch CPU scheduling error in systemd, but there's almost no documentation to be found, nor any previous cases I could rely upon.
I understand that this is not *exactly* systemd-swap related, but since the systemd module is shipped alongside it, I think it should at lease try to mitigate potential problems such as this one as much as possible.
