### ISSUE TITLE
Another issue: Timeshift won’t create snapshots if there is a Swapfile on the root partition

### ISSUE THREAD

**Issue by pheiduck** [Nefelim4ag/systemd-swap#171]
Noticed this after checking my snapshots and logs, search in the forum and found that can happen if there is a Swap File on the root partition. :(

**Comment by pheiduck** [comment]
Will test zram

**Comment by Jarel1337** [comment]
Change `swapfc_path=/var/lib/systemd-swap/swapfc/` to something that is not on your root fs

**Comment by pheiduck** [comment]
zram, works without issues, so I will use this for now :)
