### ISSUE TITLE
systemd-swap failing to start

### ISSUE THREAD

**Issue by Lampwick** [Nefelim4ag/systemd-swap#175]
![Screenshot from 2020-08-14 13-36-18](https://user-images.githubusercontent.com/8951401/90211126-33160180-de33-11ea-85ed-d7ba783d8b74.png)
I don't know why this isn't working anymore, any ideas?

**Comment by EvgenyMalikov** [comment]
![изображение](https://user-images.githubusercontent.com/32267296/90212457-ca1b9300-de0c-11ea-8143-92e94d518b46.png)
![изображение](https://user-images.githubusercontent.com/32267296/90212478-d869af00-de0c-11ea-80c1-d4ca5ee8b6de.png)

**Comment by Jarel1337** [comment]
I'm assuming this is arch linux? Go complain to the maintainer about wrong dependencies, the correct ones are in the release notes

**Comment by Jarel1337** [comment]
The aur package systemd-swap-git got the correct dependencies

**Comment by artelkr** [comment]
version 4.4.0-2 works

**Comment by Lampwick** [comment]
It's still not working for me after the update.

![Screenshot from 2020-08-14 16-52-24](https://user-images.githubusercontent.com/8951401/90222079-ac6f1d80-de4e-11ea-83e0-399693e16377.png)

**Comment by Jarel1337** [comment]
> It's still not working for me after the update.
> 
> ![Screenshot from 2020-08-14 16-52-24](https://user-images.githubusercontent.com/8951401/90222079-ac6f1d80-de4e-11ea-83e0-399693e16377.png)
> 

You haven't updated in a while it seems! Remove `/etc/systemd/swap.conf` and reinstall to get the new configuration file. Yours has been outdated for ~3 months

**Comment by EvgenyMalikov** [comment]
@Jarel1337 package from aur have same problem

**Comment by Lampwick** [comment]
Thanks @artelkr and @Jarel1337 that fixed it.

**Comment by Jarel1337** [comment]
> @Jarel1337 package from aur have same problem

Your issue seems separate, please open a new issue
