### ISSUE TITLE
On some multicore processors, Zram can cause slow start-up.

### ISSUE THREAD

**Issue by daiaji** [Nefelim4ag/systemd-swap#176]
I'm using 3900x (12c24t), and using the default configuration will result in too many zram devices to be created and mounted, and the boot speed will be very slow.
If it makes sense to create multiple zram devices, you should consider multithreading to create and mount zram devices.
I now use the parameter` zram_count=1`, the situation is relieved.

**Comment by eMPee584** [comment]
I also noticed `zram_count` being set to number of CPU cores unconditionally, which was the only way to parallelize access before the introduction of "multi stream functionality" with kernel 3.15.

Since kernel 4.7

> Regardless of the value passed to [`max_comp_streams`], ZRAM will always
> allocate multiple compression streams - one per online CPU - thus
> allowing several concurrent compression operations.
