### ISSUE TITLE
Does not allow logging in to windows manager

### ISSUE THREAD

**Issue by CrowMEV** [Nefelim4ag/systemd-swap#178]
![IMG_20200814_163303](https://user-images.githubusercontent.com/32267296/90305061-c56fe100-ded7-11ea-92b9-4998faf9a9a0.jpg)
Arch linux
I upload a photo because when systemd-swap is running, I can't login to DE

**Comment by Jarel1337** [comment]
Does commenting out scheduling=fifo in the `.service` file of systemd-swap fix this?

**Comment by EvgenyMalikov** [comment]
not help

**Comment by EvgenyMalikov** [comment]
#161 maybe it has something to do with it again

**Comment by vilgotf** [comment]
@Jturnerusa @EvgenyMalikov Could you run on latest master and see if issue still persists?

**Comment by Arjab** [comment]
I've got the same issue on a clean Arch install. Everything works fine after I enable ZRam in the swap.conf-file. After doing so and rebooting I get several journalctl-errors:
```
Dez 01 13:52:54 Fugaku systemd[1]: Failed to start Network Manager Wait Online.
Dez 01 13:52:54 Fugaku systemd[1]: systemd-logind.service: Unexpected error response from GetNameOwner(): Connection terminated
Dez 01 13:52:54 Fugaku systemd[1]: NetworkManager.service: Unexpected error response from GetNameOwner(): Connection terminated
Dez 01 13:52:54 Fugaku sddm-helper[1059]: pam_systemd(sddm-autologin:session): Failed to create session: Message recipient disconnected from message bus wi>
Dez 01 13:52:55 Fugaku sddm[897]: Failed to read display number from pipe
Dez 01 13:52:55 Fugaku sddm[897]: Could not start Display server on vt 1
Dez 01 13:54:06 Fugaku login[1104]: pam_systemd(login:session): Failed to release session: Interrupted system call
```
I've found a temporary workaround, but I'm not sure what this actually does. Maybe it's useful for somebody:
https://github.com/systemd/systemd/issues/15316#issuecomment-643599192

**Comment by oold** [comment]
Very likely that this is a bug in systemd or something else. Happens to lots of people who aren't even using systemd-swap. A comment on the systemd issue suggests they forgot to update some code after they had initially fixed the problem (https://github.com/systemd/systemd/issues/15316#issuecomment-1000842001).

**Comment by oold** [comment]
AFAIK, the systemd bug in question was fixed some time ago. I'm going to close this.
