### ISSUE TITLE
Chrome-based browsers do not use swap

### ISSUE THREAD

**Issue by taprobane99** [Nefelim4ag/systemd-swap#193]
I have systemd-swap installed on KDE Plasma and it seeems that Chrome and Opera will use existing physical RAM but both have crashed tabs with an "out of memory" message when no more is available (but plenty of swap space is). The issue is not present with other browsers (Firefox) or other programs. Is there a solution for this?

**Comment by vilgotf** [comment]
Seems to be a feature of chrome, I'd change browser :)
