### ISSUE TITLE
systemd-swap.conf ERROR

### ISSUE THREAD

**Issue by talesam** [Nefelim4ag/systemd-swap#20]
Hello, Linux Manjaro, your script is in error, if I uncomment these two lines:

```
# $ {Sys [cpu_count]} #
# $ {Sys [ram_size]} # in KB
```

It gives error that the command does not exist:

[talesam@neit ~]$ systemctl status systemd-swap.service
● systemd-swap.service - Manage swap spaces on zram, files and partitions.
   Loaded: loaded (/usr/lib/systemd/system/systemd-swap.service; enabled; vendor preset: disabled)
   Active: active (exited) (Result: exit-code) since Sex 2016-05-13 02:31:28 BRT; 6s ago
  Process: 2454 ExecStop=/usr/lib/systemd/scripts/systemd-swap.sh stop (code=exited, status=0/SUCCESS)
  Process: 2465 ExecStart=/usr/lib/systemd/scripts/systemd-swap.sh start (code=exited, status=127)
 Main PID: 2465 (code=exited, status=127)

Mai 13 02:31:28 neit systemd[1]: Started Manage swap spaces on zram, files and partitions..
Mai 13 02:31:28 neit systemd-swap.sh[2465]: /etc/systemd-swap.conf: line 12: 4: comando não encontrado
Mai 13 02:31:28 neit systemd[1]: systemd-swap.service: Main process exited, code=exited, status=127/n/a

**Comment by Nefelim4ag** [comment]
This lines is a description, you don't need uncomment it.
It's only for understanding what this variables means.

**Comment by Nefelim4ag** [comment]
I made update of config description:
https://github.com/Nefelim4ag/systemd-swap/commit/eea05b26d132c4f1e1a51e24969ede4731afa454

**Comment by talesam** [comment]
Thanks!

```
[talesam@neit teamviewer]$ cat /proc/swaps 
Filename				Type		Size	Used	Priority
/dev/sda2                               partition	2097148	0	-1
/dev/zram0                              partition	956792	7152	32767
```

It is on only one core, was to catch 4. Another thing I found was not more detail on the configuration of this file.

There is a "standard" configuration most appropriate? Because the file is all commented.

**Comment by Nefelim4ag** [comment]
@talesam,
zram have max_comp_streams attribute
```
/sys/block/zram0/max_comp_streams:4 # this is count of threads
```
By default all options disabled and have a values what are very close to default values for appropriate subsystems (for zram module as example)

**Comment by talesam** [comment]
I got it, thanks!
