### ISSUE TITLE
Manjaro Linux: Failed to start Manage swap spaces; ModuleNotFoundError: No module named 'sysv_ipc'

### ISSUE THREAD

**Issue by slrslr** [Nefelim4ag/systemd-swap#213]
On latest Linux Manjaro (6.11.11-1-MANJARO arch: x86_64) started an issue:

$ sudo systemd-swap
```
Traceback (most recent call last):
  File "/usr/bin/systemd-swap", line 24, in <module>
    import sysv_ipc
ModuleNotFoundError: No module named 'sysv_ipc'
```

and:
`systemd[1]: Failed to start Manage swap spaces on zram, files and partitions...`

README.md page is not showing steps to uninstall the systemd-swap... I have possibly installed it using "sudo pamac install systemd-swap"

**Comment by oold** [comment]
Your Python is missing `sysv_ipc`. It's a requirement for this script and should be installed by your package manager if that's the source for `systemd-swap`. Furthermore, this script hasn't seen any maintenance in years. It's likely you'll run into other issues.
As for uninstalling: https://github.com/nefelim4ag/systemd-swap?tab=readme-ov-file#file-location. That is, unless whatever you installed was modified to put the files somewhere else.

**Comment by slrslr** [comment]
Thanks, I have removed said package (sudo pamac remove systemd-swap) and it removed all yours linked files:
`file /etc/systemd/swap.conf /usr/lib/systemd/system/systemd-swap.service /usr/bin/systemd-swap`

Then there was a zram-generator: sudo pamac search zram
```
zram-generator  1.2.1-1                                                                                                                                                                  extra
    Systemd unit generator for zram devices
```

Installing it: sudo pamac install zram-generator
It appears that I will have to find out how to configure it. It does not work out of the box https://github.com/systemd/zram-generator/issues/221
