### ISSUE TITLE
[bug] zswap compressor

### ISSUE THREAD

**Issue by mattia-b89** [Nefelim4ag/systemd-swap#22]
I configured systemd-swap to use zswap by uncommenting these four lines:
`zswap[enabled]=1
zswap[compressor]=lz4
zswap[max_pool_percent]=15
zswap[zpool]=zbud`

unfortunately dmesg reports a different compressor:
`[    0.296973] zswap: loaded using pool lzo/zbud`

**Comment by Nefelim4ag** [comment]
~$ grep . /sys/module/zswap/parameters/*

**Comment by mattia-b89** [comment]
ok!
thank you for the explaination!
