### ISSUE TITLE
[improvement] enhance configuration file

### ISSUE THREAD

**Issue by mattia-b89** [Nefelim4ag/systemd-swap#25]
reading the recent change, is not clear at all why should I do those changes.
I'm talking about VM settings of swappiness and overcommit
with the same reason I'd like to better explain the Swap devices part: the little description is not clear...

**Comment by Nefelim4ag** [comment]
Check at now please

**Comment by mattia-b89** [comment]
ok, it's better than before, it's a begin!
I'd like to understand the `vm.overcommit_memory=1` setting
and why do you suggest to increase `vm.swappiness` since this would handle of deeper use of the swap?

**Comment by Nefelim4ag** [comment]
I change nothing about vm.overcommit_memory

But i change description for vm.swappiness
```
## If zram/zswap used -> try increase vm.swappiness
## For zram it decrease chances to get too early OOM
## For zswap it's can clear more memory for disk io cache
```

**Comment by Nefelim4ag** [comment]
Config file has been rewritten.
Thanks.
