### ISSUE TITLE
Debian package.sh different umask

### ISSUE THREAD

**Issue by coelner** [Nefelim4ag/systemd-swap#26]
Hey,

I use the umask=027, so this error happens:
`dpkg-deb: error: control directory has bad permissions 750 (must be >=0755 and <=0775)`
After adding line 15:
`chmod 755 $DEB_NAME/DEBIAN`
the error is gone.

**Comment by Nefelim4ag** [comment]
https://github.com/Nefelim4ag/systemd-swap/commit/ae923d494de7ba43c237d9f5669c2fcf311c336d
Thanks.
