### ISSUE TITLE
Debian package.sh dpkg duplicate entry

### ISSUE THREAD

**Issue by coelner** [Nefelim4ag/systemd-swap#27]
If you run the package.sh script multiple times, the following error occurs:
```
dpkg-deb: error: parsing file 'systemd-swap-2.27.2_any/DEBIAN/control' near line 10 package 'systemd-swap':
 duplicate value for `Package' field
```
Change line 16:
echo "Package: systemd-swap"    >> $DEB_NAME/DEBIAN/control
to
echo "Package: systemd-swap"    > $DEB_NAME/DEBIAN/control

Result: the control file is newly created on each run.

**Comment by Nefelim4ag** [comment]
https://github.com/Nefelim4ag/systemd-swap/commit/e7f40d39ea43aedc55a6e914065ad63ed2005f9e
Thanks.
