### ISSUE TITLE
clarify "swapd_auto_swapon" parameter

### ISSUE THREAD

**Issue by mattia-b89** [Nefelim4ag/systemd-swap#32]
Hi,
I'd like to understand if we need to have `swapd_auto_swapon=1` even if swap are already mounted by systemd... I have the swap partition entry in the /etc/fstab file...

**Comment by Nefelim4ag** [comment]
This is just duplicate functionality of systemd and fstab.
On GPT, if you have swap partitions, systemd will automount it without entry in fstab, but only 1 swap partition.

You can leave it on, it will not break anything (or disable it, as you wish).

**Comment by mattia-b89** [comment]
Thank you,
We may add these useful information in the swap.conf file

powered by CM
