### ISSUE TITLE
Add more documentation

### ISSUE THREAD

**Issue by variadico** [Nefelim4ag/systemd-swap#34]
Cool project.

Could you add more documentation? There are some unanswered questions in the Arch Wiki about systemd-swap.

https://wiki.archlinux.org/index.php/Talk:Swap#systemd-swap

Here are some of the key questions.

* What's the difference between Swap File Universal and Swap File Chunked?
* Do we need to activate both zram and zswap?
* Do we need both swapfu and swapfc?
* When would we want a certain configuration?
* Where is the swap file located?
* Can we use this to enable hibernation?

**Comment by Nefelim4ag** [comment]
@variadico,
Where is the swap file located? https://github.com/Nefelim4ag/systemd-swap/blob/master/swap.conf#L39
And https://github.com/Nefelim4ag/systemd-swap/commit/593aab8b16f7c35319baf1cce31e1f5d8a0c84a9

**Comment by variadico** [comment]
Sweet! Thank youuu!!! 👍
