### ISSUE TITLE
Swap fails to start after syntax error with sleep. 

### ISSUE THREAD

**Issue by mirrornoir** [Nefelim4ag/systemd-swap#35]
Hi, I'm using systemd-swap with Zswap and Swap File Chunked. Recently after noticing some performance issues I saw that swap was no longer activated (htop showing 0k/0k when normally it would show 0k/256MB if swap was active but not in use). I checked the output of journalctl and found this:

```Feb 17 05:55:27 valkyrie systemd-swap[1173]: INFO: Check config
Feb 17 05:55:27 valkyrie systemd-swap[1173]: INFO: Backup config
Feb 17 05:55:27 valkyrie systemd-swap[1173]: INFO: Load config
Feb 17 05:55:27 valkyrie systemd-swap[1173]: INFO: Zswap: backup current configuration: start
Feb 17 05:55:29 valkyrie systemd-swap[1173]: INFO: Zswap: backup current configuration: complete
Feb 17 05:55:29 valkyrie systemd-swap[1173]: INFO: Zswap: set new parameters: start
Feb 17 05:55:29 valkyrie systemd-swap[1173]: INFO: Zswap: set new parameters: complete
Feb 17 05:55:29 valkyrie systemd-swap[1173]: INFO: swapD: searching swap devices
Feb 17 05:55:30 valkyrie systemd-swap[1173]: sleep: missing operand
Feb 17 05:55:30 valkyrie systemd-swap[1173]: Try 'sleep --help' for more information.
```

It looks like there's just a syntax error preventing it from starting. I am using Arch Linux and I can provide more information if needed. I'd love to get this fixed for my low memory laptop. Thanks for the hard work on this fantastic daemon.

**Comment by Nefelim4ag** [comment]
@mirrornoir, check your config for updates

**Comment by mirrornoir** [comment]
Whoops, updated my config and it's working just fine. This issue can be closed, thanks for the help.
