### ISSUE TITLE
Poorly used grep for users with different language than the English (system locale)

### ISSUE THREAD

**Issue by domker** [Nefelim4ag/systemd-swap#36]
I found a small bug in your systemd-swap script.
`/usr/bin/systemd-swap: linia 172: (*100)/(+1) : błąd składni: spodziewany argument (błędny znacznik t...`

I'm polish Linux Manjaro user.
You have declared statically "free -b | grep Swap:" in 172 script line.
"grep" doesn't return nothing.

> 
> $free -b
> 
> Result:
>              razem       użyte       wolne    dzielone   buf/cache    dostępne
> Pamięć:        3387         838        1560         177         988        2130
> **Wymiana:**        2047           0        2047

If you see - grep word "SWAP" is polished -> no "SWAP" but "Wymiana"

....and your script make a new chunks.

I changed the word to Polish counterpart and the script works properly.

**Comment by Nefelim4ag** [comment]
@domker, try latest release

**Comment by domker** [comment]
Thanks - solved :)
I'm using "systemd-swap" community package from Arch now, becouse in Manjaro repository last version of package is 3.2.0-1.
Now works great :)
