### ISSUE TITLE
swapfc_frequency seems to block the service from stopping

### ISSUE THREAD

**Issue by Craeckie** [Nefelim4ag/systemd-swap#38]
When shutting down it often/always waits for systemd-swap to exit.
This seems to be caused by [`sleep $swapfc_frequency` in systemd-swap](https://github.com/Nefelim4ag/systemd-swap/blob/9f843c41a185b8972470e8ce828cadffea936b59/systemd-swap#L297-L298).

Does this serve any purpose?

**Comment by Nefelim4ag** [comment]
```
swapfc_frequency=1s         # How often check free swap space
```
you have a problem with 2s wait?

Yes, that ensure that loop with swapfc will stopped
https://github.com/Nefelim4ag/systemd-swap/blob/9f843c41a185b8972470e8ce828cadffea936b59/systemd-swap#L218

And if you wait more then 2s, that mean systemd-swap try swapoff files

**Comment by Craeckie** [comment]
ok, makes sense. I thought it could save power, but looking at the script it looks like that shouldn't make any difference.
