### ISSUE TITLE
Syntax error found after updating to version 3.4

### ISSUE THREAD

**Issue by Nightbane112** [Nefelim4ag/systemd-swap#39]
I've recently updated this package to version 3.4 and saw this error pop-up when checking the status of this service after restarting it.

`Aug 21 23:43:24 Ideapad-310 systemd-swap[7901]: /run/systemd/swap/swap.conf: line 30: /4: syntax error: operand expected (error token is "/4") `

After some checking, I found out the affecting line of code is as shown below. Should I be concern of the error above? I am currently not using the ZRam function but it is good to know if it will cause any problems.

https://github.com/Nefelim4ag/systemd-swap/blob/185e050dd8372451b08692f7ecffa12fd8c1765e/swap.conf#L30

**Comment by Nefelim4ag** [comment]
@Nightbane112, thanks, i'm stupid.
Try 3.4.1: https://github.com/Nefelim4ag/systemd-swap/commit/1193a452ed0ecac50839db7ad2d4a228e82ccefc

**Comment by Nightbane112** [comment]
@Nefelim4ag Can confirm that this branch fixes the errors. Thank you very much. 

Output from journalctl -xe after adding the patch and restarting the service.

    -- Unit systemd-swap.service has begun shutting down.
    Aug 22 11:56:49 Ideapad-310 systemd-swap[30897]: INFO: Load config
    Aug 22 11:56:52 Ideapad-310 systemd-swap[30897]: INFO: Zswap: restore configuration: start
    Aug 22 11:56:52 Ideapad-310 systemd-swap[30897]: INFO: Zswap: restore configuration: complete
    Aug 22 11:56:52 Ideapad-310 systemd[1]: Stopped Manage swap spaces on zram, files and partitions..
    -- Subject: Unit systemd-swap.service has finished shutting down
    -- Defined-By: systemd
    -- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
    -- 
    -- Unit systemd-swap.service has finished shutting down.
    Aug 22 11:56:52 Ideapad-310 systemd[1]: Started Manage swap spaces on zram, files and partitions..
    -- Subject: Unit systemd-swap.service has finished start-up
    -- Defined-By: systemd
    -- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
    -- 
    -- Unit systemd-swap.service has finished starting up.
    -- 
    -- The start-up result is done.
    Aug 22 11:56:52 Ideapad-310 sudo[30893]: pam_unix(sudo:session): session closed for user root
    Aug 22 11:56:52 Ideapad-310 systemd-swap[30953]: INFO: Check config
    Aug 22 11:56:52 Ideapad-310 systemd-swap[30953]: INFO: Backup config
    Aug 22 11:56:52 Ideapad-310 systemd-swap[30953]: INFO: Load: /etc/systemd/swap.conf.d/10-enable-swapfc.conf
    Aug 22 11:56:52 Ideapad-310 systemd-swap[30953]: INFO: Load config
    Aug 22 11:56:52 Ideapad-310 systemd-swap[30953]: INFO: Zswap: backup current configuration: start
    Aug 22 11:56:52 Ideapad-310 systemd-swap[30953]: INFO: Zswap: backup current configuration: complete
    Aug 22 11:56:52 Ideapad-310 systemd-swap[30953]: INFO: Zswap: set new parameters: start
    Aug 22 11:56:52 Ideapad-310 systemd-swap[30953]: INFO: Zswap: set new parameters: complete
    Aug 22 11:56:52 Ideapad-310 systemd-swap[30953]: INFO: swapD: searching swap devices
    Aug 22 11:56:53 Ideapad-310 systemd-swap[30953]: INFO: swapFC: free swap: 0 < 15 - allocate chunk: 1
