### ISSUE TITLE
Faild to start var-lib-systemd-swap-swapfc--1.swap

### ISSUE THREAD

**Issue by cerebrux** [Nefelim4ag/systemd-swap#41]
Today I did a fresh Arch installation (no GUI) on a VM and then installed systemd-swap (3.5.0-1)
with the following config options:

`zswap_enabled=0`
 `swapfc_enabled=1`

I checked my system and saw that now swap files where active. 
checked the output of htop and saw a process was still running 

`shred -n1 -z /var/lib/systemd-swap/swapfc//1`

While investigating I looked again to htop and saw that the number has changed:

`shred -n1 -z /var/lib/systemd-swap/swapfc//8` 

So I thought that something is wrong with swapfc trying to create(?) ckunks and failing. Then tries again  but fails.

I checked _sudo systemctl status systemd-swap_ and the output gave me a hint:

`Faild to start var-lib-systemd-swap-swapfc--1.swap: Unit  var-lib-systemd-swap-swapfc--1.swap is not loaded properly: Invalid argument.
See system logs and systemctl status var-lib-systemd-swap-swapfc--1.swap
`
And the above was repeated for every chunk

So, I run systemctl status var-lib-systemd-swap-swapfc--1.swap and there was:

`Value of What= and unit name do not match, not loading`

Any ideas how to investigate this ?

On my main machine I have systemd-swap (3.4.2-1) with the same config options and It is working properly. 
Could this be a regression ?

**Comment by Nefelim4ag** [comment]
@cerebrux, please test:
https://github.com/Nefelim4ag/systemd-swap/commit/2b2d2d4247351cf534f261e8620a134b4fd555a1

**Comment by Nefelim4ag** [comment]
That will do a trick:
https://github.com/Nefelim4ag/systemd-swap/commit/1c94123a0fbc7c6931ccad3e6fd1751d0259f8a9

**Comment by cerebrux** [comment]
@Nefelim4ag I cloned your repo with your latest additions and installed it. Work like as expected !

Thank for your patience and valuable time addressing the issue !

**Comment by Nefelim4ag** [comment]
@cerebrux https://github.com/Nefelim4ag/systemd-swap/releases/tag/3.5.1

**Comment by billniakas** [comment]
Everything seems to be working fine now 👍
