### ISSUE TITLE
Why is protectHome set to true in the unit file ?

### ISSUE THREAD

**Issue by saponace** [Nefelim4ag/systemd-swap#42]
Hi,

I noticed you've set the `protectHome` flag to `true` in the systemd unit file. Is there a reason to do so ?

I assume setting it to `read-only` would actually be better since it would allow people to link the config files from their homedir to /etc/systemd/swap.conf.d/ .

**Comment by Nefelim4ag** [comment]
When i added that, my logic was simple:
Must systemd-swap change in /home? -> Not, so i will add protectHome.

If you wish, you can send a PR.

**Comment by saponace** [comment]
Thanks for your feedback. I created [PR#43](https://github.com/Nefelim4ag/systemd-swap/pull/43).
