### ISSUE TITLE
get_fs_type() simplification

### ISSUE THREAD

**Issue by WonderWoofy** [Nefelim4ag/systemd-swap#45]
I just started looking at the scripting for this cool little project and I noticed you used the following to determine the filesystem type:
```
    get_fs_type(){ stat -f "$1" | grep Type: | tr -s ' ' | cut -d' ' -f7; }
```
This just happens to be something I looked into a while back and so it immedately jumped out at me as overly complicated. Stat is the right tool, but you can simply make use of the amazing formatting options it gives:
```
    get_fs_type(){stat --file-system --format="%T" "$1"}
```
...or even shorter:
```
    get_fs_type(){stat -fc "%T" "$1"}
```

**Comment by Nefelim4ag** [comment]
@WonderWoofy, thanks!
Looks good to me =)
Can you create PR for that?
```
get_fs_type(){ stat -fc "%T" "$1"; }
```

**Comment by WonderWoofy** [comment]
Sure thing, it was just the middle of the night when I commented. I should have been sleeping as it was...

I'll do this after work.

**Comment by Nefelim4ag** [comment]
@WonderWoofy,
too long %)
https://github.com/Nefelim4ag/systemd-swap/commit/d0c78ddfd1d6f2cc068ab1bcfb99e45215c28777

Any way, thanks!

**Comment by WonderWoofy** [comment]
Agreed. I totally forgot!

I intend to read through the rest of your script though. It is very
organized looking, I like it.

-- 
curtisshima [at] gmail [dot] com
