### ISSUE TITLE
README is out of date

### ISSUE THREAD

**Issue by kynikos** [Nefelim4ag/systemd-swap#49]
Hi, I'm not sure if you're already working on it, but the 4.0.0 release left README.md out of date, it still mentions Swap File Universal in the configuration section even though 4a1706aa3b9e5b70543a5f1ff3470eb72c4a4e64 merged swapfu into swapfc. Also, can you clarify how to update the old swap.conf for those who were making use of the swapfu options?

**Comment by Nefelim4ag** [comment]
@kynikos, you are right about that i forgot to update README.
So: https://github.com/Nefelim4ag/systemd-swap/commit/6af72476aaf8009a88edbffa36bb8ec20fdd750d

**Comment by kynikos** [comment]
Thank you, that solves the issue for me, closing it.
