### ISSUE TITLE
Support for /usr/lib/systemd/swap.conf.d/*.conf

### ISSUE THREAD

**Issue by abouvier** [Nefelim4ag/systemd-swap#62]
Can you support `*.conf` files in `/usr/lib/systemd/swap.conf.d/`? Like other systemd components (`coredump.conf`, `journald.conf`, etc.). This would allow a package to ship a custom configuration outside of `/etc`.

**Comment by Nefelim4ag** [comment]
Already supported IIRC

**Comment by Nefelim4ag** [comment]
That's depends on target system, i.e. on debian that will be /lib/...

Yes, easy.
PR are always welcomed.
