### ISSUE TITLE
Rewrite on python

### ISSUE THREAD

**Issue by Nefelim4ag** [Nefelim4ag/systemd-swap#66]
systemd-swap make more complex over time and i think it's time for rewrite in on python to simplify.

**Comment by hakavlad** [comment]
Why not Rust?

**Comment by Nefelim4ag** [comment]
@hakavlad, why not ASM? :)

I just know Python/Golang, python are more easy to support and update,
that's not a micro service, or high load server - just simple automation script

So that will be cool if we leave things simple, more people know bash/python, because they simple and enough for their tasks.

i.e. please, understood me correctly: I just don't know Rust, and currently not have enough free time and desire to learn it.  (And time for rewrite, of course :) )

**Comment by oold** [comment]
Just a quick heads-up. I'm interested in doing the Python rewrite and have already started working on it. I'll post a PR once my code is in a usable state, probably the next few days.
