### ISSUE TITLE
Add support for swapfiles on btrfs in Linux 5.0+

### ISSUE THREAD

**Issue by Nefelim4ag** [Nefelim4ag/systemd-swap#67]
We must add some logic to understand the system and change our behaviour.

**Comment by hartmark** [comment]
You can probably close this as it's working for me on a system with only btrfs

**Comment by Nefelim4ag** [comment]
@hartmark, btrfs now support swapfiles like other FS, but systemd-swap doesn't allow that

**Comment by dustinwilson** [comment]
The latest systemd has added fixes for btrfs and swap files, including with hibernation. I have systemd-swap working on a btrfs system in an EndeavourOS vm following your instructions in the readme with one exception that I picked up from the Arch wiki: `swapfc_force_preallocated=1`. It seems to work at the moment. I'm new to this, but I'd be willing to test.

**Comment by Nefelim4ag** [comment]
#92

**Comment by Jarel1337** [comment]
Closing since implemented
