### ISSUE TITLE
Questions about swap.conf

### ISSUE THREAD

**Issue by ShapeShifter499** [Nefelim4ag/systemd-swap#68]
I want to run this on my Arch Linux laptop and other server but I have a couple of questions about the config.

At the top of the swap.conf file it mentions
```
# You can override any settings by files in:
# /etc/systemd/swap.conf.d/*.conf
```
Does the file name matter? i.e. /etc/systemd/swap.conf.d/settings.conf would work?
Does format matter?  I only include the variables I want to override?

I ask because the ArchWiki here https://wiki.archlinux.org/index.php/Swap#systemd-swap
suggests to edit the swap.conf file directly but your own swap.conf suggests otherwise.

**Comment by Nefelim4ag** [comment]
This is just a file mask, i.e. yep `/etc/systemd/swap.conf.d/settings.conf ` would work.
You can redefine any var from swap.conf, or can just copy swap.conf to new location,
and then make local changes if you like.

**Comment by ShapeShifter499** [comment]
Alright super, thanks for the quick answers!
