### ISSUE TITLE
Minimum swap space

### ISSUE THREAD

**Issue by innovate-invent** [Nefelim4ag/systemd-swap#72]
I run software that allocates RAM faster than the swap can be allocated. The only way to set a minimum swap space is to set the chunk size to the minimum. Please add a parameter to force a minimum number of chunks or have a larger initial chunk.

**Comment by Nefelim4ag** [comment]
@innovate-invent, you can just set large chunk at start.

About preallocated chunks number, possible. But you can just same preallocate swap by some other way.
