### ISSUE TITLE
swapfc_max_count must be in range 1..32, but swap.conf says "0 - unlimited"

### ISSUE THREAD

**Issue by goekce** [Nefelim4ag/systemd-swap#74]

**Comment by jocull** [comment]
Is unlimited (`0`) a valid value? Does it work?

**Comment by goekce** [comment]
I do not use systemd-swap anymore since opening this issue.

I just installed systemd-swap, set swapfc_max_count to 0 and run memtester. Unfortunately systemd-swap did not get triggered, so I cannot test if 0 works or not.

**Comment by Nefelim4ag** [comment]
Linux kernel has hard-coded limit.
Oh, that's my fault.

**Comment by ShapeShifter499** [comment]
so should I be setting 32 instead of 0?

**Comment by Jarel1337** [comment]
This should not be set to 0 as it would not create a single swapfile. This was an old documentation error.
