### ISSUE TITLE
Swap not taking the load from RAM, memory exception on high load app 

### ISSUE THREAD

**Issue by ruathudo** [Nefelim4ag/systemd-swap#77]
I have to read big file whose memory is increasing so fast. When the data is fill up full of my 16G ram, the usages in swap is only 800M. Then the app crash.
It seems swap is handling the data too late or too slow.
I see this problem is similar to the issue #76 . I installed the latest version from master and set up the config like this:
```
swapfc_enabled=1
swapfc_force_use_loop=0     # Force usage of swapfile + loop
swapfc_frequency=1s         # How often check free swap space
swapfc_chunk_size=5G     # Allocate size of swap chunk
swapfc_max_count=32         # 0 - unlimited, note: 32 is a kernel maximum
swapfc_free_swap_perc=30    # Add new chunk if free < 15%
```
My swapiness is 50, so it shouldn't take too late for swap to be used.
Thank you!

**Comment by Nefelim4ag** [comment]
That's not work as you think.

If something bot goes to swap, that the kernel decision.

If you think, your app MUST go to swap, you must ask kernel or app developer about that.

**Comment by ruathudo** [comment]
I'm running jupyter notebook to read big csv file by Pandas python. 
It used to work with swapspace package. However, it only works when I'm using remote ssh to run the notebook, if I run directly from browser then it is killed before Ram is full. Swapspace is pretty old, auto increase but not auto decrease swap files after uses. So I would give a try with this one as it looks promising.

**Comment by ruathudo** [comment]
@Nefelim4ag I solved the problem by using different library (dask) instead of pandas to read big csv file. Now the swapfc work flawlessly. Thanks.
