### ISSUE TITLE
Publish on Ubuntu repository?

### ISSUE THREAD

**Issue by yxliang01** [Nefelim4ag/systemd-swap#82]
This software has already published on archlinux main repository. Would be great to see if this is also on Ubuntu official repository!

**Comment by Nefelim4ag** [comment]
@yxliang01, i can't help with that, you need to talk with Debian/Ubuntu maintainers

**Comment by yxliang01** [comment]
@Nefelim4ag  Hmm Is it? So, it's not like the author submits to them, then they will see whether they want to do it and keep maintaining?

**Comment by Nefelim4ag** [comment]
@yxliang01, you can read how to submit pkgs to debian.
AFAIK, without help of some maintainer i can't push package.
- - -
https://lists.debian.org/debian-mentors/2016/05/msg00261.html
