### ISSUE TITLE
[feature request] add a warning about dmesg and lz4

### ISSUE THREAD

**Issue by mattia-b89** [Nefelim4ag/systemd-swap#84]
connected with: https://github.com/Nefelim4ag/systemd-swap/issues/46

I think it is a good idea add a warning about this _non-issue_,
inside the README, in the zswap section, a thing like this:
```
[...]
kernel defaults to lzo and if you have set up to use lz4, it will be loaded later in the boot process;
this means `dmesg | grep zswap` return lzo instead of lz4; this is normal.
to check the correct configuration execute `sudo systemd-swap status`
if you want to load lz4 early in the boot process you have to add modules `lz4 lz4_compress` in the ramdisk and add `zswap.compressor=lz4` to your kernel parameters
[...]
```

reported here too: https://wiki.archlinux.org/index.php/Zswap#Compression_algorithm

**Comment by Jarel1337** [comment]
Closing since this seems like a niche issue and zstd should (always?) be used instead of lz4. If you really care about this feel free to @ me.
