### ISSUE TITLE
"swapd_auto_swapon=0" is not respected in local config files

### ISSUE THREAD

**Issue by chungy** [Nefelim4ag/systemd-swap#94]
In order to keep the package-installed version of `/etc/systemd/swap.conf` pristine, I use `/etc/systemd/swap.conf.d/local.conf` to override settings.

Setting `swapd_auto_swapon=0` in this file has no effect; systemd-swap still finds and activates disk swap partitions and leads to undesirable behavior. Only changing it in the main `swap.conf` file will alter the program's behavior to what I want.

I use block devices (zfs volumes) for virtual machines and these swap partitions becoming activated automatically is potentially disasterous if the host and guests are sharing the same swap volume.

**Comment by Jarel1337** [comment]
Closing since it's fixed by #124 or #126.
